name: time_weights_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - colorama=0.4.6
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=1.2.0
  - ipykernel=6.15.0
  - ipython=8.14.0
  - jedi=0.18.2
  - jupyter_client=7.0.6
  - jupyter_core=5.3.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libopenblas=0.3.20
  - libsodium=1.0.18
  - llvmlite=0.40.0
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - numba=0.57.0
  - openssl=1.1.1u
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.0.1
  - platformdirs=3.8.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - pynndescent=0.5.10
  - python=3.9.16
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyzmq=19.0.2
  - readline=8.2
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tornado=6.1
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing_extensions=4.6.3
  - tzdata=2022g
  - umap-learn=0.5.3
  - wcwidth=0.2.6
  - wheel=0.38.4
  - xz=5.2.10
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
    - absl-py==1.4.0
    - accelerate==0.20.3
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - async-timeout==4.0.2
    - attrs==22.2.0
    - charset-normalizer==3.1.0
    - click==8.1.3
    - cloudpickle==2.2.1
    - cvxopt==1.3.2
    - cvxpy==1.3.2
    - cylp==0.91.6
    - datasets==2.10.1
    - dill==0.3.6
    - ecos==2.0.12
    - evaluate==0.4.0
    - filelock==3.9.0
    - frozenlist==1.3.3
    - fsspec==2023.3.0
    - ftfy==6.1.1
    - gurobipy==10.0.2
    - huggingface-hub==0.13.1
    - idna==3.4
    - joblib==1.2.0
    - kaggle==1.5.13
    - mosek==10.1.9
    - multidict==6.0.4
    - multiprocess==0.70.14
    - nltk==3.8.1
    - numpy==1.24.2
    - open-clip-torch==2.16.0
    - ortools==9.4.1874
    - osqp==0.6.3
    - overrides==7.3.1
    - packaging==23.0
    - pandas==1.5.3
    - peft==0.3.0
    - pillow==9.4.0
    - protobuf==3.20.3
    - psutil==5.9.5
    - pyarrow==11.0.0
    - python-slugify==8.0.1
    - pytz==2022.7.1
    - pyyaml==6.0
    - qdldl==0.1.7.post0
    - regex==2022.10.31
    - requests==2.28.2
    - responses==0.18.0
    - rouge-score==0.1.2
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - scs==3.2.3
    - sentencepiece==0.1.97
    - submitit==1.4.5
    - text-unidecode==1.3
    - threadpoolctl==3.1.0
    - timm==0.6.12
    - tokenizers==0.13.2
    - torch==1.13.1
    - torchvision==0.14.1
    - transformers==4.27.4
    - typing-extensions==4.5.0
    - urllib3==1.26.15
    - xxhash==3.2.0
    - yarl==1.8.2
